### ISSUE TITLE
JSON.decoder errors

### ISSUE THREAD

**Issue by cybert79** [dlfernando/Instagram-downloader#2]
resume.txt temporary file created.
--->nickylaenen<---
--->3720986463<---
---><---
--->0<---
Traceback (most recent call last):
  File "instagram_downloader.py", line 89, in <module>
    nexttoken = download_photos(instagram_username, user_id, nexttoken, pag)
  File "instagram_downloader.py", line 41, in download_photos
    for match in r.json()["media"]:
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dlfernando** [comment]
Hi there,
I have just tried script with instagram username "nickylaenen" as you provided and works ok. Try again and be sure to remove temporary filename "resume.txt" created inside folder because executing script.
